test: test-tutorial test-brackets

test-tutorial:
	poetry run python -c 'import doctest; doctest.testfile("Tutorial.md")'

test-brackets:
	poetry run python -c 'import doctest; doctest.testfile("Brackets.md")'
