test: test-tutorial test-brackets test-illustrated

test-tutorial:
	poetry run python -c 'import doctest; doctest.testfile("Tutorial.md")'

test-brackets:
	poetry run python -c 'import doctest; doctest.testfile("Brackets.md")'

test-illustrated:
	poetry run python -c 'import doctest; doctest.testfile("Illustrated.md")'
